implements stale update warning
GrapheneOS/platform_packages_apps_Updater pull request #14
Opened 2019-12-14 02:21 UTC by renlord

show warning notification when updater fails to reach update server for more than 1 day

2019-12-31 13:04 UTC, chirayudesai requested changes
One more thing that could be done is show the last update check time below the "Check for updates" button.

Can show it at
https://github.com/GrapheneOS/platform_packages_apps_Updater/blob/10/src/app/seamlessupdate/client/Settings.java#L55
using
https://developer.android.com/reference/android/preference/Preference#setSummary(java.lang.CharSequence)

2019-12-31 13:04 UTC, chirayudesai commented on res/values/strings.xml
> +    <string name="notification_updater_contact_fail_title">Update Stale Warning</string>
How about "Failed to check for updates"

2019-12-31 13:04 UTC, chirayudesai commented on src/app/seamlessupdate/client/Service.java
> +            if (System.currentTimeMillis() - getLastUpdateCheckTime > ONEDAY) {
`getLastUpdateCheckTime()`

2020-01-01 10:50 UTC, renlord commented on res/values/strings.xml
> +    <string name="notification_updater_contact_fail_title">Update Stale Warning</string>
applied your suggested changes.

2020-01-01 10:51 UTC, renlord commented on src/app/seamlessupdate/client/Service.java
> +            if (System.currentTimeMillis() - getLastUpdateCheckTime > ONEDAY) {
thanks for pointing out the typo

2020-03-08 09:35 UTC, renlord commented
closes https://github.com/GrapheneOS/os_issue_tracker/issues/161

2020-06-05 08:01 UTC, thestinger commented
Needs to be rebased @renlord. Still need to think about this though.

2020-10-05 00:21 UTC, closed without merging

2021-03-31 09:13 UTC, renlord commented
@thestinger no interest to accept this feature? or approach incorrect?